import random #Importing random library so as to generate a random integer to be guessed
import math #Importing math librabry for math functions

#Taking input of range from the user
lower=int(input("Enter the lower bound of the range:"))
upper=int(input("Enter the upper bound of the range:"))

#Generating a random integer in the given range
number=random.randint(lower,upper)

#Determining how many tries a user will get to guess the number correctly
#So the User gets log of the total number of integers falling in the range, with base 2
number_of_tries=int(math.log(upper-lower+1,2));
print("You have",number_of_tries,"number of tries to guess correctly")

#Loop for guessing the number
for i in range(number_of_tries):
    n=int(input("Guess an integer:")) #taking input of the guessed number from the user
    if n==number: # checking if the number guessed by the user is same as the random integer generated by the computer
        print("Your guessed correctly in",i+1,"tries!!")
        break;
    else:
        if n>number:
            print("You guessed too high!")
        else:
            print("You guessed too low!")
else:
    print()
    print("You are out of tries!")
    print("The number was",number)
    print("Better luck next time!!")
    
